site_name: Himmelblau
site_url: https://himmelblau-idm.org
theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: indigo
  font:
    text: Poppins
    code: Courier Prime
  logo: assets/himmelblau_logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  custom_dir: overrides
extra_css:
  - css/custom.css
  - assets/feedback.css
extra_javascript:
  - assets/feedback.js
nav:
  - Home: index.md
  - Downloads: downloads.md
  - Documentation: /docs/
  - Community: community.md
  - Why Himmelblau?: why.md
  - Donations: donations.md
  - Blog: blog.md
  - About: about.md
plugins:
  - search
extra:
  social:
    - icon: material/github
      link: https://github.com/himmelblau-idm/himmelblau
    - icon: material/matrix
      link: https://matrix.to/#/#himmelblau:matrix.org
    - icon: material/linkedin
      link: https://www.linkedin.com/in/davidmmulder/
    - icon: material/email
      link: dmulder@himmelblau-idm.org
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@dmulder
repo_url: https://github.com/himmelblau-idm/himmelblau
repo_name: Himmelblau
