site_name: Himmelblau Documentation
theme:
  name: readthedocs
  custom_dir: overrides
plugins:
  - search
  - awesome-pages
repo_url: https://github.com/himmelblau-idm/site.git
repo_name: Himmelblau Documentation
edit_uri: https://github.com/himmelblau-idm/site/edit/main/mkdocs/docs
site_url: https://himmelblau-idm.org/docs
